[clipboard] add share button to clipboard url
OswaldoPineda/Today_I_learned pull request #37
Opened 2023-11-13 17:05 UTC by JuanequeX

## Quick Info
- Add clipboard.js to enable a button that automatically copies the relative path of each post to the clipboard, allowing users to easily share this specific TIL post with the community.

## Screenshots (if apply)

https://github.com/OswaldoPineda/Today_I_learned/assets/50384228/f99ae51e-4246-4541-b39c-2be593845c1f

2023-11-13 17:20 UTC, OswaldoPineda requested changes

2023-11-13 17:20 UTC, OswaldoPineda commented on app/javascript/clipboard_config.js
> +import ClipboardJS from 'clipboard';
change var variables to const

2023-11-13 17:24 UTC, JuanequeX commented on app/javascript/clipboard_config.js
> +import ClipboardJS from 'clipboard';
DONE

2023-11-13 17:26 UTC, OswaldoPineda submitted a review, later dismissed

2023-12-07 00:45 UTC, JuanequeX commented
please give me an overview to unblock this PR, because this branch was pushed to production currently. @OswaldoPineda

2024-01-06 19:28 UTC, OswaldoPineda approved these changes
LGTM!

2024-01-06 19:31 UTC, merged